services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: pgvector-db
    environment:
      POSTGRES_USER: tennoheika
      POSTGRES_PASSWORD: jinping8964
      POSTGRES_DB: blog
    ports:
      - '5432:5432'
    volumes:
      - ./sample-data:/sample-data
