services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: hyperagent-pg
    environment:
      POSTGRES_USER: tennoheika
      POSTGRES_PASSWORD: jinping8964
      POSTGRES_DB: hyperagent
    ports:
      - '5432:5432'
    volumes:
      - ./lib/db/data:/var/lib/postgresql/data
